spring:
  # \u914D\u7F6E\u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/sys?characterEncoding=UTF8&useSSL=false&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    druid:
      max-active: 10
      min-idle: 2
      validation-query: select 'x'
      stat-view-servlet:
        login-username: admin
        enabled: true
        login-password: admin
        allow:
        deny:
        url-pattern: /druid/*
  # \u8BBE\u7F6E\u65F6\u95F4\u683C\u5F0F
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper\u914D\u7F6E
pagehelper:
  helper-dialect: mysql
  reasonable: true
